-- 0004_appointments.sql — a scheduled (or requested) service visit.
--
-- status lifecycle:
--   requested  → customer proposed up to N preferred slots (request mode)
--   scheduled  → has a confirmed scheduled_start/_end
--   completed  → the visit happened
--   canceled   → called off
--   no_show    → customer wasn't there
CREATE TABLE IF NOT EXISTS appointments (
  id              BIGSERIAL PRIMARY KEY,
  tenant_id       BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  customer_id     BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  service_type_id BIGINT REFERENCES service_types(id) ON DELETE SET NULL,
  subscription_id BIGINT,  -- set when generated by a recurring plan (FK added in 0006)

  status          TEXT NOT NULL DEFAULT 'scheduled',
  booking_mode    TEXT NOT NULL DEFAULT 'instant',  -- instant | request
  source          TEXT NOT NULL DEFAULT 'online',   -- online | admin | recurring

  scheduled_start TIMESTAMPTZ,
  scheduled_end   TIMESTAMPTZ,
  -- For request-mode bookings: up to N proposed windows the customer would accept.
  requested_slots JSONB NOT NULL DEFAULT '[]'::jsonb,

  service_address TEXT,
  notes           TEXT,          -- customer-supplied notes
  internal_notes  TEXT,          -- staff-only
  price_cents     INTEGER NOT NULL DEFAULT 0,  -- estimate snapshot from the service

  google_event_id TEXT,
  access_token    TEXT,          -- customer self-service link token

  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at    TIMESTAMPTZ,
  canceled_at     TIMESTAMPTZ,
  canceled_reason TEXT
);
CREATE INDEX IF NOT EXISTS idx_appointments_tenant_start ON appointments (tenant_id, scheduled_start);
CREATE INDEX IF NOT EXISTS idx_appointments_tenant_status ON appointments (tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_appointments_customer ON appointments (customer_id);
