-- 0005_invoicing.sql — the revamped invoicing model.
--
-- Design goals (per the product brief):
--   • Fully customizable balance: line_items is a JSONB array staff freely edit,
--     seeded from customizable presets.
--   • No automated pre-appointment balance reminders anywhere.
--   • An invoice/balance is only ever sent when staff request it from the dash.
--   • financial_events is an append-only ledger; amount_paid is derived from it.

CREATE TABLE IF NOT EXISTS invoices (
  id                BIGSERIAL PRIMARY KEY,
  tenant_id         BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  customer_id       BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  appointment_id    BIGINT REFERENCES appointments(id) ON DELETE SET NULL,
  subscription_id   BIGINT,  -- set when generated by a recurring plan

  number            TEXT NOT NULL,
  status            TEXT NOT NULL DEFAULT 'draft',  -- draft | sent | partial | paid | void
  currency          TEXT NOT NULL DEFAULT 'USD',

  -- [{ label, description, quantity, unit_amount_cents, amount_cents, taxable }]
  line_items        JSONB NOT NULL DEFAULT '[]'::jsonb,
  subtotal_cents    INTEGER NOT NULL DEFAULT 0,
  discount_cents    INTEGER NOT NULL DEFAULT 0,
  tax_rate_percent  NUMERIC(6,3) NOT NULL DEFAULT 0,
  tax_cents         INTEGER NOT NULL DEFAULT 0,
  total_cents       INTEGER NOT NULL DEFAULT 0,
  amount_paid_cents INTEGER NOT NULL DEFAULT 0,

  notes             TEXT,
  terms             TEXT,
  due_date          DATE,
  access_token      TEXT NOT NULL,

  stripe_payment_intent_id TEXT,
  stripe_checkout_session_id TEXT,
  stripe_payment_link_id   TEXT,
  stripe_payment_link_url  TEXT,

  created_by        TEXT,
  sent_at           TIMESTAMPTZ,
  paid_at           TIMESTAMPTZ,
  voided_at         TIMESTAMPTZ,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_invoices_tenant_number ON invoices (tenant_id, number);
CREATE INDEX IF NOT EXISTS idx_invoices_tenant_status ON invoices (tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_invoices_customer ON invoices (customer_id);
CREATE INDEX IF NOT EXISTS idx_invoices_appointment ON invoices (appointment_id);

-- Append-only money ledger. Positive amounts are payments, negative are refunds.
CREATE TABLE IF NOT EXISTS financial_events (
  id             BIGSERIAL PRIMARY KEY,
  tenant_id      BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  invoice_id     BIGINT REFERENCES invoices(id) ON DELETE CASCADE,
  customer_id    BIGINT REFERENCES customers(id) ON DELETE SET NULL,
  event_type     TEXT NOT NULL,             -- payment | refund | adjustment
  amount_cents   INTEGER NOT NULL,          -- signed
  method         TEXT,                      -- card | cash | check | stripe | other
  note           TEXT,
  stripe_ref     TEXT,
  external_ref   TEXT,                       -- idempotency key for webhook events
  created_by     TEXT,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_financial_events_invoice ON financial_events (invoice_id);
CREATE INDEX IF NOT EXISTS idx_financial_events_tenant ON financial_events (tenant_id, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS idx_financial_events_external_ref
  ON financial_events (tenant_id, external_ref) WHERE external_ref IS NOT NULL;
